///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#if wxCHECK_VERSION(3, 1, 6)
    #include <wx/bmpbndl.h>
#else
    #include <wx/bitmap.h>
#endif

#include <wx/sizer.h>

#include "proddatautilframe.h"

bool ProdDataUtilFrameBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{

    if (!wxFrame::Create(parent, id, title, pos, size, style, name))
        return false;

    m_menubar = new wxMenuBar();

    m_menu = new wxMenu();
    m_menubar->Append(m_menu, wxGetStockLabel(wxID_HELP));

    SetMenuBar(m_menubar);

    m_statusBar = CreateStatusBar();

    auto* box_sizer5 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* box_sizer2 = new wxBoxSizer(wxHORIZONTAL);

    m_static_text = new wxStaticText(this, wxID_ANY, "Begin");
    box_sizer2->Add(m_static_text, wxSizerFlags().Border(wxALL));

    m_date_pickerBegin = new wxDatePickerCtrl(this, wxID_ANY, wxDefaultDateTime, wxDefaultPosition,
        wxDefaultSize, wxDP_DROPDOWN|wxDP_SHOWCENTURY);
    box_sizer2->Add(m_date_pickerBegin, wxSizerFlags().Border(wxALL));

    box_sizer->Add(box_sizer2, wxSizerFlags().Expand().Border(wxALL));

    auto* box_sizer3 = new wxBoxSizer(wxHORIZONTAL);

    m_static_text2 = new wxStaticText(this, wxID_ANY, "End");
    box_sizer3->Add(m_static_text2, wxSizerFlags().Border(wxALL));

    m_date_pickerEnd = new wxDatePickerCtrl(this, wxID_ANY, wxDefaultDateTime, wxDefaultPosition,
        wxDefaultSize, wxDP_DROPDOWN|wxDP_SHOWCENTURY|wxDP_DEFAULT);
    box_sizer3->Add(m_date_pickerEnd, wxSizerFlags().Border(wxALL));

    m_btnSearch = new wxButton(this, wxID_ANY, "Search");
    box_sizer3->Add(m_btnSearch, wxSizerFlags().Border(wxALL));

    box_sizer->Add(box_sizer3, wxSizerFlags().Expand().Border(wxALL));

    box_sizer5->Add(box_sizer, wxSizerFlags().Expand().Border(wxALL));

    auto* box_sizer4 = new wxBoxSizer(wxHORIZONTAL);

    m_gridProduct = new wxGrid(this, wxID_ANY, wxDefaultPosition, ConvertDialogToPixels(wxSize(150, 200)));
    {
        m_gridProduct->CreateGrid(5, 3);
        m_gridProduct->EnableEditing(false);
        m_gridProduct->EnableDragGridSize(true);
        m_gridProduct->SetMargins(0, 0);
        #if wxCHECK_VERSION(3, 1, 4)
            m_gridProduct->SetDefaultCellFitMode(wxGridFitMode::Clip());
        #endif
        m_gridProduct->SetDefaultCellAlignment(wxALIGN_RIGHT, wxALIGN_CENTER);
        m_gridProduct->SetColLabelAlignment(wxALIGN_CENTER, wxALIGN_CENTER);
        m_gridProduct->SetColLabelSize(wxGRID_AUTOSIZE);

        m_gridProduct->SetRowLabelAlignment(wxALIGN_CENTER, wxALIGN_CENTER);
        m_gridProduct->SetRowLabelSize(wxGRID_AUTOSIZE);
    }
    box_sizer4->Add(m_gridProduct, wxSizerFlags().Border(wxALL));

    m_tree_ctrlProduct = new wxTreeCtrl(this, wxID_ANY, wxDefaultPosition,
        ConvertDialogToPixels(wxSize(200, 200)));
    box_sizer4->Add(m_tree_ctrlProduct, wxSizerFlags().Border(wxALL));

    box_sizer5->Add(box_sizer4, wxSizerFlags().Expand().Border(wxALL));

    auto* box_sizer6 = new wxBoxSizer(wxHORIZONTAL);

    m_gridTotalCount = new wxGrid(this, wxID_ANY);
    {
        m_gridTotalCount->CreateGrid(5, 3);
        m_gridTotalCount->EnableEditing(false);
        m_gridTotalCount->EnableDragGridSize(true);
        m_gridTotalCount->SetMargins(0, 0);
        #if wxCHECK_VERSION(3, 1, 4)
            m_gridTotalCount->SetDefaultCellFitMode(wxGridFitMode::Clip());
        #endif
        m_gridTotalCount->SetDefaultCellAlignment(wxALIGN_RIGHT, wxALIGN_CENTER);
        m_gridTotalCount->SetColLabelAlignment(wxALIGN_CENTER, wxALIGN_CENTER);
        m_gridTotalCount->SetColLabelSize(wxGRID_AUTOSIZE);

        m_gridTotalCount->SetRowLabelAlignment(wxALIGN_CENTER, wxALIGN_CENTER);
        m_gridTotalCount->SetRowLabelSize(100);
    }
    box_sizer6->Add(m_gridTotalCount, wxSizerFlags().Border(wxALL));

    box_sizer5->Add(box_sizer6, wxSizerFlags().Border(wxALL));

    m_img = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition,
        ConvertDialogToPixels(wxSize(500, 500)));
    box_sizer5->Add(m_img, wxSizerFlags().Border(wxALL));
    SetSizerAndFit(box_sizer5);

    Centre(wxBOTH);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
