///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/datectrl.h>
#include <wx/dateevt.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>
#include <wx/grid.h>
#include <wx/menu.h>
#include <wx/spinbutt.h>
#include <wx/statbmp.h>
#include <wx/stattext.h>
#include <wx/statusbr.h>
#include <wx/treectrl.h>
#include "wx/stockitem.h"

class ProdDataUtilFrameBase : public wxFrame
{
public:
    ProdDataUtilFrameBase() {}
    ProdDataUtilFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString,
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_FRAME_STYLE, const wxString &name = wxFrameNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString,
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_FRAME_STYLE, const wxString &name = wxFrameNameStr);

protected:

    // Class member variables

    wxButton* m_btnSearch;
    wxDatePickerCtrl* m_date_pickerBegin;
    wxDatePickerCtrl* m_date_pickerEnd;
    wxGrid* m_gridProduct;
    wxGrid* m_gridTotalCount;
    wxMenu* m_menu;
    wxMenuBar* m_menubar;
    wxSpinButton* m_spin_btn;
    wxStaticBitmap* m_img;
    wxStaticText* m_static_text2;
    wxStaticText* m_static_text;
    wxStatusBar* m_statusBar;
    wxTreeCtrl* m_tree_ctrlProduct;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
