///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <wx/sizer.h>

#include "proddatautilframe.h"

bool ProdDataUtilFrame::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{

    if (!wxFrame::Create(parent, id, title, pos, size, style, name))
        return false;

    m_menubar = new wxMenuBar();

    m_menu = new wxMenu();
    m_menubar->Append(m_menu, wxGetStockLabel(wxID_HELP));

    SetMenuBar(m_menubar);

    m_statusBar = CreateStatusBar();

    auto* box_sizer = new wxBoxSizer(wxVERTICAL);
    SetSizerAndFit(box_sizer);

    Centre(wxBOTH);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
